### ISSUE TITLE
Read binaries fail

### ISSUE THREAD

**Issue by sarasally** [lwang-astro/PeTar#14]
The method suggested to get binaries from files generated from petar.data.process gives the following errors:

p1 = petar.Particle(interrupt_mode='bse')
p2 = petar.Particle(interrupt_mode='bse')
binary =petar.Binary(p1,p2)
binary.loadtxt([binary data file path])

IN my case I tried with file "data.200.binary"

>>> import petar
>>> p1 = petar.Particle(interrupt_mode='bse')
>>> p2 = petar.Particle(interrupt_mode='bse')
>>> binary =petar.Binary(p1,p2)
>>> binary.loadtxt('data.200.binary',skiprows=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tank0/rastello/NEWPETAR2021/PeTar/include/petar/base.py", line 324, in loadtxt
    self.readArray(dat_int, **kwargs)
  File "/tank0/rastello/NEWPETAR2021/PeTar/include/petar/base.py", line 124, in readArray
    self.__dict__[key].readArray(_dat, icol, **kwargs)
  File "/tank0/rastello/NEWPETAR2021/PeTar/include/petar/base.py", line 128, in readArray
    self.__dict__[key] = _dat[:,icol].astype(parameter)
IndexError: index 51 is out of bounds for axis 1 with size 50
>>> 
It seems there are less columns than expected.

**Comment by lwang-astro** [comment]
In your script, the `interrupt_mode='bse'` indicates that you have switch on BSE in the simulation. 
The missing of columns suggests that there is probably no Stellar evolution columns in data.200.binary (should be 78 columns).
Is your simulation using BSE? Besides, when you use petar.data.process to generate binary snapshot, have you also included the bse option (-i bse) in petar.data.process commander?

**Comment by sarasally** [comment]
Thank you! now it works!
