### ISSUE TITLE
Running petar.find.dt with bse enabled

### ISSUE THREAD

**Issue by JoRdAnB421** [lwang-astro/PeTar#21]
I am having some problems understanding the error from the `check.perf.test.log` file when I run the `petar.find.dt` tool on my cluster (which I created from `mcluster`). This is the command that I submitted:

`petar.find.dt -o 8 -a "--stellar-evolution 1 --detect-interrupt"  ../mcluster/test_10000_run.txt.input`

and this fails after a single time step with the error message in `check.perf.test.log`  as follows:

![image](https://user-images.githubusercontent.com/72075850/145560470-878dc839-9f5c-4a57-93f2-40e7fffb8ad0.png)

I am not sure what I am doing wrong here and so any assistance is much appreciated.

**Comment by lwang-astro** [comment]
The option used in petar.find.dt is incorrect. `--detect-interrupt` requires one argument. But you don't need to provide '--stellar-evolution' and '--detect-interrupt' if the default values are used.

**Comment by JoRdAnB421** [comment]
Okay I see, thank you for the clarification! Can I check what the default values are for these two parameters?

**Comment by JoRdAnB421** [comment]
As an extra comment, I have added the parameter required for `--detect-interrupt`  so that the command line reads:

`petar.find.dt -m 2 -o 8 -a "--stellar-evolution 1 --detect-interrupt 1"  ../mcluster/test_10000_run.txt.input`

This resolves the error I was facing before, however presents a new issue in the log files:

![image](https://user-images.githubusercontent.com/72075850/145581990-e2922577-c07c-447f-a3df-cccf7f17e336.png)

Thank you very much for your help.

**Comment by lwang-astro** [comment]
Which fortran compiler did you use? For gfortran, I did not get this error.

**Comment by JoRdAnB421** [comment]
As far as I am aware I am also using gfortran.

**Comment by lwang-astro** [comment]
Are you using Mac OS?

**Comment by lwang-astro** [comment]
I did not got this error in Linux. One simple solution is comment out the line 23-25 
```
23      do K=0,14
24         write(*,*) ktype(k,:)
25      end do
```
in bse-interface/bse/print_const.f

**Comment by JoRdAnB421** [comment]
I am running this on a computing cluster which uses Linux, I will try commenting out those lines and see if that helps. 

Thanks for your help
