### ISSUE TITLE
Bad Termination Error

### ISSUE THREAD

**Issue by JoRdAnB421** [lwang-astro/PeTar#22]
When running, I occasionally receive a `BAD TERMINATION` error, pictured below. Is this the large step warning mentioned in the ReadMe (my runs are using stellar evolution) or a result of some other error? And is the best solution to simply restart with fewer cpu cores? 

![image](https://user-images.githubusercontent.com/72075850/145974648-693d5db2-05ae-44a3-96ec-fad2bdd5e5ee.png)

Thanks for your help

**Comment by JoRdAnB421** [comment]
I have tried restarting the run from the previous snapshot with fewer cpu's and it will sometimes proceed for a few more steps before it crashes again with the same errors.

**Comment by lwang-astro** [comment]
Hi, this problem happens when the newest FDPS (v7.1) is used. Could you try to use the old version of FDPS v7.0?

**Comment by JoRdAnB421** [comment]
Hi, so I have tried to use the FDPS v7.0 and I have still received the same error. 

In order to use the older version I simply cloned the FDPS directory and then use `git checkout 6fedb4b` which is the id for the v7.0 commit is this an appropriate way to select the older version for use? I am not aware of another way to clone an older version of a github repo.

Thanks

**Comment by lwang-astro** [comment]
In FDPS directory, you can `git checkout v7.0`. If the version is successfully switched. When you run petar, the output log will show the FDPS version v7.0 inside the FDPS logo.

**Comment by JoRdAnB421** [comment]
Hello again,

I have run into a similar error now when running the `petar.find.dt` tool, though it has an exit code 11 rather than the 6 I was getting before.
![image](https://user-images.githubusercontent.com/72075850/146558369-6d06557e-5f42-4013-9fe0-ce972afc25ae.png)
I am using the v7.0 FDPS package as you can see:
![image](https://user-images.githubusercontent.com/72075850/146558447-df65f04f-7ba8-473b-ba0d-452a32b49f19.png)

**Comment by lwang-astro** [comment]
There is no useful error message from your log. Can you successfully run a test sample without petar.finddt? If the test run is fine. Then your option for petar.find.dt may not be correct.
