### ISSUE TITLE
BSE on M2 chip 

### ISSUE THREAD

**Issue by christianboily** [lwang-astro/PeTar#39]
Hi Long Wang, 

I have success with PeTar on an M2 processor (+mpi, galpy, amp) but without the BSE module which breaks 
down at compilation : 

mpicxx-openmpi-gcc12 -D BSEBBF -D BSE_BASE -fpermissive  -O3 -Wall -std=c++17 -fopenmp bse_test.cxx -o petar.bse -L./ -lbse -lgfortran
In file included from /opt/local/include/gcc12/c++/cassert:44,
                 from bse_interface.h:4,
                 from bse_test.cxx:7:
bse_interface.h: In member function 'bool BSEManager::checkParams()':
bse_interface.h:1088:16: error: 'trackmode' was not declared in this scope
 1088 |         assert(trackmode>0);
      |                ^~~~~~~~~
make[1]: *** [petar.bse] Error 1
make: *** [bse-interface/libbse.a] Error 2

--> this seems like a brutal mistake, a parameter that fails to initialise : never had that before and am wondering 
--> if the fault is with gcc12 ? That's the default version I can install with MacPorts (to have the mpi wrapper). 

Any idea what may be causing this ? I have cloned PeTar (as well as FDPS and SDAR) to have the latest versions of 
the stable branches in each case. 

Cheers, chris b.

**Comment by christianboily** [comment]
Re- in fact, the configuration with interrupt set to bseEmp (not bse) works fine : the track mode fnc is defined and the code compiles ok.

**Comment by lwang-astro** [comment]
Hi chris,

Thank you for pointing out this. It is a bug introduced from last update of BSEEMP. I have fixed the issue. You can now compile BSE.

**Comment by christianboily** [comment]
Dear Long Wang, thank you! We are interested in extreme metal poor stars here, too, cf. The Pristine survey, and it's great to have both libraries for comparison : keep up the good work! 


Cheers, Chris b.


----- Mail d’origine -----
De: lwang-astro ***@***.***>
À: lwang-astro/PeTar ***@***.***>
Cc: christian boily ***@***.***>, Author ***@***.***>
Envoyé: Thu, 01 Jun 2023 09:05:06 +0200 (CEST)
Objet: Re: [lwang-astro/PeTar] BSE on M2 chip  (Issue #39)

Hi chris,

Thank you for pointing out this. It is a bug introduced from last update of BSEEMP. I have fixed the issue. You can now compile BSE.
