### ISSUE TITLE
petar.movie: default value of -m not working?

### ISSUE THREAD

**Issue by kaiwu-astro** [lwang-astro/PeTar#40]
Hi! I am trying petar.movie .  I have installed ffmpeg and imageio[ffmpeg] as backend. When I run this command
```
size_=8; petar.movie -i bse -t galpy --generate-binary 2 --x-min -$size_ --x-max $size_ --y-min -$size_ --y-max $size_ snapList
```
It gives empty figures and an empty movie like this:

![data 1](https://github.com/lwang-astro/PeTar/assets/18334656/e1c27e84-599e-4fb5-a7d2-cb48585fd760)

If I explicitly set ```-m x-y``` then it produces figures and movie correctly.

```
size_=8; petar.movie -m x-y -i bse -t galpy --generate-binary 2 --x-min -$size_ --x-max $size_ --y-min -$size_ --y-max $size_ snapList
```

![iShot_2023-07-11_16 38 27](https://github.com/lwang-astro/PeTar/assets/18334656/e5469d95-724b-4e3b-83f2-e6eb5556e626)

I noticed that the help message says ```-m``` has default value of ```x-y```, but it seems I need to explicitly set this kwarg. Is it my problem or there is something wrong?

**Comment by lwang-astro** [comment]
Thanks for the report. The help message is an old version, the new version of petar.movie should always use -m option. I will update the help message.

**Comment by kaiwu-astro** [comment]
Another small thing is that: ```petar.data.process``` supports both ```-i``` and ```--interrupt-mode```; both ```-t``` and ```--external-mode```, while only the short form is supported in ```petar.movie```. I personally love the long option form to avoid confusion to myself. It would be nice to add support of the long form in ```petar.movie``` as well. 

#41

**Comment by lwang-astro** [comment]
I have checked and found this is a bug. Now it is fixed and the default plot is -m x-y

**Comment by kaiwu-astro** [comment]
Thank you for fixing this, and thank you for considering my suggestions 👍
