### ISSUE TITLE
Correct pronunciation of "PeTar"?

### ISSUE THREAD

**Issue by kaiwu-astro** [lwang-astro/PeTar#42]
Sorry to disturb for this tiny issue. Recently I will give a presentation and mention PeTar many times. Previously I heard two versions of saying "PeTar": /'pe tα:(r)/  and  /pi: 'tα:(r)/  but I cannot decide which one to use. This is torturing me when I rehearse my talk 😭. Could you please tell me how to pronounce it correctly? (and if you like, you may annotate the pronunciation in the README)

**Comment by lwang-astro** [comment]
It does not matter much. You can use /pi: 'tα:(r)/
