### ISSUE TITLE
```Lagrangian``` with shell mode

### ISSUE THREAD

**Issue by HerculeWu** [lwang-astro/PeTar#45]
Dear Long Wang,

When I use the python data analysis tool, I found one issue about lagrangian. 

In the class ```Lagrangian``` (defined in PeTar/analysis/lagrangian.py), when use ```calcOneSnapshot``` with shell mode, the variabe ```nlagr``` (line 393, 394) denotes number of particles between two neighbor Lagrangian radii. Then ```n_offset``` (line 435) works not properly. Maybe this issue can be fixed by changing line 435 to
```
if shell_mode:
    n_offset = np.append(np.zeros(1), rindex+1).astype(int)
else:
    n_offset = np.append(np.zeros(1),nlagr).astype(int)
```

Thanks and with best wishes,
Wu

**Comment by lwang-astro** [comment]
Thank you for pointing out this bug. Indeed the usage of `nlagr` to determing `n_offset` is not correct. It should be `rindex+1`.  I have modified the line 435 to `n_offset = np.append(np.zeros(1), rindex+1).astype(int)`.
