### ISSUE TITLE
Back calculations using PeTar

### ISSUE THREAD

**Issue by jikrant3** [lwang-astro/PeTar#49]
We want to back calculate the positions of a small Nbody system (only dynamics, no stellar evolution is needed).
Is there a way to do back-calculations using PeTar? We tried giving negative time-steps, which does not work. 

If there is a workaround, do let us know.

**Comment by lwang-astro** [comment]
PeTar does not support negative time steps, but you can reverse the velocities of each star to integrate backwards instead of using a negative time step.
