### ISSUE TITLE
error running star_cluster.sh

### ISSUE THREAD

**Issue by marlito-gonaldo-byte** [lwang-astro/PeTar#52]
Hello, 
I am trying to run the script star_cluster.sh on TU Dresden HPC but I keep getting errors.
My config.log file : 
[config.log](https://github.com/user-attachments/files/15903116/config.log)

I slightly modified star_cluster.sh to  : 
```
#!/bin/bash

export mclusterDir=/projects/p_s_blackhole/workspace/mcluster

# use mcluster to generate a star cluster with the initial condtion: N=1000 Kroupa (2001) IMF, 95% binary (Kroupa 1995 a,b Sana 2012 ..., see mcluster manual) 
# The initial condition for NBODY6++GPU is created with -C 5, this is used to generated initial condtion for PeTar
$mclusterDir/mcluster -N 1000 -b 0.95 -C 5 -u 1 >mc.log

# use petar.init to create initial data for petar.
# the mcluster option '-u 1' generate data in astronomical unit (Msun, pc, km/s), but petar requires a self-consistent unit of velocity: pc/Myr, '-v kms2pcmyr' will do this.
petar.init -v kms2pcmyr -f input test.dat.10

# Use PeTar to execute the simulation.
# Use '-t 100.0' to run the simulation for 100 Myr.
# Use '-o 5' to generate output snapshots every 5 Myr.
# Use '-u 1' to set the units to astronomical units (Msun, pc, pc/Myr).
# Use '-b 500' to specify the number of primordial binaries as 500.
# By default, OpenMP utilizes all CPU threads. If you wish to use a specific number of threads, please add 'OMP_NUM_THREADS=[number of threads]'."
OMP_STACKSIZE=128M petar -u 1 -b 500 -t 100.0 -o 5.0 input &>output

# after mode finished, gether the output data and do post-data process to detect binaries, obtain Lagrangian and core radii and corresponding properties.
# To maintain consistent units during post-processing, use '-G 0.00449830997959438' to set the gravitational constant to astronomical units.
petar.data.gether data
petar.data.process -G 0.00449830997959438 data.snap.lst

```

When I run script as follow : `srun --nodes=1 --ntasks=1 --cpus-per-task=4 --gres=gpu:1 --gpus-per-task=1 --time=01:00:00 --mem-per-cpu=1443 --partition=alpha /projects/p_s_blackhole/workspace/PeTar/sample/star_cluster.sh`

I get this output : 
```
srun: job 334586 queued and waiting for resources
srun: job 334586 has been allocated resources
Transfer "test.dat.10" to PeTar input data file "input"
Skip rows: 0
Add stellar evolution columns: no
Unit convert: distance scale: 1.0;  mass scale: 1.0;  velocity scale: 1.022712165045695
/data/horse/ws/mago247f-py_venv_PeTar/bin/petar.init: line 130: input: Input/output error
awk: cmd. line:1: (FILENAME=input.scale__ FNR=54) fatal: print to "standard output" failed (Input/output error)
/projects/p_s_blackhole/workspace/PeTar/sample/star_cluster.sh: line 19: output: Input/output error
data filename prefix: data
data.esc
data.sse
data.bse
data.mosse
data.mobse
data.sseEmp
data.bseEmp
Traceback (most recent call last):
  File "/data/horse/ws/mago247f-py_venv_PeTar/bin/petar.data.process", line 7, in <module>
    import petar
ModuleNotFoundError: No module named 'petar'
srun: error: i8026: task 0: Exited with exit code 1
```

**Comment by lwang-astro** [comment]
`ModuleNotFoundError: No module named 'petar'` This means that you have not correctly setup PYTHONPATH for python analysis tool, so that petar module is not found in python too petar.data.process. Please follow the suggestion in the README to setup PYTHONPATH first. In addition, it seems that you have running the script by using srun, please also make sure that the PYTHONPATH is correctly set in the computing node.

**Comment by marlito-gonaldo-byte** [comment]
Thank you, I fixed this issue. Now I am able to run star_cluster.sh however I have this as an output : 
```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 4
slots that were requested by the application:

  petar

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
--------------------------------------------------------------------------
```

Here is how I call PeTar in star_cluster.sh : 
`OMP_STACKSIZE=128M OMP_NUM_THREADS=8 mpiexec -n 4 petar -u 1 -b 500 -t 100.0 -o 5.0 input &>output`
I run star_cluster.sh the same way I mentioned in my previous message. 

I am using the cluster [Alpha Centauri](https://compendium.hpc.tu-dresden.de/jobs_and_resources/hardware_overview/) (short: Alpha) by NEC provides AMD Rome CPUs and NVIDIA A100 GPUs and is designed for AI and ML tasks.
34 nodes, each with :
- 8 x NVIDIA A100-SXM4 Tensor Core-GPUs
- 2 x AMD EPYC CPU 7352 (24 cores) @ 2.3 GHz, Multithreading available
- 1 TB RAM (16 x 32 GB DDR4-2933 MT/s per socket)
- 3.5 TB local memory on NVMe device at /tmp

So, I get that `mpiexec -n 4` request the 4 CPU and I only have 2 CPU per node, thus should I replace the srun configuration by `--nodes=2 --ntasks=2 --cpus-per-task=2` in order to utilise 4 CPU as asked here `mpiexec -n 4` ? 
My question might be naive but I am new to the use of HPC and I wan't to optimise properly the program.
Also I don't think I am using GPU here, because `CUDA_VISIBLE_DEVICES=` is missing from star_cluster.sh. 
In my case I could use up to 8xN_nodes GPU ? 
using `CUDA_VISIBLE_DEVICES=7` in star_cluster.sh and `--gres=gpu:8 --gpus-per-task=8` in my job ressource configuration ?

**Comment by lwang-astro** [comment]
In addition, it is better to try step by step. First use no MPI, no GPU and only OMP. If it works properly, then try with MPI+OMP no GPU, and finally try MPI+OMP+GPU.

**Comment by marlito-gonaldo-byte** [comment]
I compiled the code with only OpenMPI as follow : `./configure --prefix=/data/horse/ws/mago247f-py_venv_PeTar --with-mpi=no  --with-simd=auto --with-fdps-prefix=/projects/p_s_blackhole/workspace/FDPS --with-sdar-prefix=/projects/p_s_blackhole/workspace/SDAR`

But the output of the simulation is as follow : 
```
     //==================================\\
     ||                                  ||
     || ::::::: ::::::. ::::::. .::::::. ||
     || ::      ::    : ::    : ::       ||
     || ::::::  ::    : ::::::'  `:::::. ||
     || ::      ::::::' ::      `......' ||
     ||     Framework for Developing     ||
     ||        Particle Simulator        ||
     ||     Version 7.0 (2021/08)        ||
     \\==================================//

       Home   : https://github.com/fdps/fdps 
       E-mail : fdps-support@mail.jmlab.jp
       Licence: MIT (see, https://github.com/FDPS/FDPS/blob/master/LICENSE)
       Note   : Please cite the following papers.
                - Iwasawa et al. (2016, Publications of the Astronomical Society of Japan, 68, 54)
                - Namekata et al. (2018, Publications of the Astronomical Society of Japan, 70, 70)

       Copyright (C) 2015 
         Masaki Iwasawa, Ataru Tanikawa, Natsuki Hosono,
         Keigo Nitadori, Takayuki Muranushi, Daisuke Namekata,
         Kentaro Nomura, Junichiro Makino and many others
******** FDPS has successfully begun. ********

 ******************************************
  ██████╗ ███████╗████████╗ █████╗ ██████╗
  ██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗
  ██████╔╝█████╗     ██║   ███████║██████╔╝
  ██╔═══╝ ██╔══╝     ██║   ██╔══██║██╔══██╗
  ██║     ███████╗   ██║   ██║  ██║██║  ██║
  ╚═╝     ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝
 ******************************************
Version: 1238_295r
============== PeTar ================
 Online document: (preparing)
 GitHub page: https://github.com/lwang-astro/PeTar
 License: MIT
 Please cite the following papers when you use PeTar for any publications
    FDPS: see above FPDS Logo message
    SDAR: Wang L., Nitadori K., Makino J., 2020, MNRAS, 493, 3398
    PeTar: Wang L., Iwasawa M., Nitadori K., Makino J., 2020, MNRAS, 497, 536
 Copyright (C) 2017
    Long Wang, Masaki Iwasawa, Keigo Nitadori, Junichiro Makino and many others
=====================================
Use quadrupole moment in tree force calculation
Use 3rd order tidal tensor method
Use Pseudoparticle multipole method
Use orbit-dependent neighbor criterion
Check energy of short-range (hard) integration
Count isolated particles in hard clusters
Use SIMD
Calculate profile
Use AR TTL method
Use slowdown Tree method
Use slowdown timescale criterion
Print adjust group information
=====================================
Input data unit, 0: unknown, referring to G; 1: mass:Msun, length:pc, time:Myr, velocity:pc/Myr:   1
Number of primordial binaries for initialization (assuming the binaries' IDs are 1,2*n_bin):   500
End time of simulation:   100
Output time interval for particle dataset snapshots:   5
Reading data file name: input
----- Finish reading input options of PeTar -----
----- Parallelization information -----
MPI processors: 1
OMP threads:    6
Error: Ptcl data reading fails! requiring data number is 4, only obtain 2.
Check your input data, whether the consistent features (interrupt mode and external mode) are used in configuring petar and the data generation
```
I am using cluster to generate the cluster, see star_cluster.sh on the 1st message.

**Comment by marlito-gonaldo-byte** [comment]
I see there is a closed topic on this error, I will look into it, try to solve my issue and close this topic if I solve it.

**Comment by marlito-gonaldo-byte** [comment]
Hello, I have now issues with mpi.
Here is how I config : .`/configure --prefix=/data/horse/ws/mago247f-test_PeTar_mpi --with-mpi=yes  --with-simd=auto --with-fdps-prefix=/projects/p_s_blackhole/workspace/FDPS --with-sdar-prefix=/projects/p_s_blackhole/workspace/SDAR`

here is how petar is called in a modified version of star_cluster.sh script : 
```
export OMP_STACKSIZE=128M
export OMP_NUM_THREADS=2
mpiexec -n 6 petar -u 1 -b 500 -t 100.0 -o 5.0 input &>output
```

Here is how I run the script : `sbatch --nodes=1 --ntasks-per-node=6 --cpus-per-task=2 --gres=gpu:1 --hint=multithread --time=01:00:00 --mem-per-cpu=1443  --partition=alpha /projects/p_s_blackhole/workspace/PeTar/sample/star_cluster_mpi.sh`

Here is the slurm output : 
```
cat slurm-413777.out 
Transfer "test.dat.10" to PeTar input data file "input"
Skip rows: 0
Add stellar evolution columns: no
Unit convert: distance scale: 1.0;  mass scale: 1.0;  velocity scale: 1.022712165045695
data filename prefix: data
data.esc
data.sse
data.bse
data.mosse
data.mobse
data.sseEmp
data.bseEmp
G : 0.00449830997959438
filename_prefix : data
lagr data is saved in file: data.lagr
core data is saved in file: data.core
esc_single data is saved in file: data.esc_single
esc_binary data is saved in file: data.esc_binary
CPU time profile:
read 0.0
find_pair 0.0
density 0.0
center_core 0.0
save_data 0.0
calc_pot 0.0
lagr 0.0
escaper 0.0
bse 0.0
```

And here is the PeTar output :
```
 --------------------------------------------------------------------------
WARNING: Could not generate an xpmem segment id for this process'
address space.

The vader shared memory BTL will fall back on another single-copy
mechanism if one is available. This may result in lower performance.

  Local host: i8023
  Error code: 2 (No such file or directory)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 2 with PID 269194 on node i8023 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
[i8023:269184] 5 more processes have sent help message help-btl-vader.txt / xpmem-make-failed
[i8023:269184] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
6 total processes killed (some possibly by mpiexec during cleanup)
```

**Comment by lwang-astro** [comment]
The command and script look fine. The error from PeTar indicates a problem of MPI environment: "Could not generate an xpmem segment id for this process". Not sure what it means. Maybe you can first try to use the sbatch command with the same options `sbatch --nodes=1 --ntasks-per-node=6 --cpus-per-task=2 --gres=gpu:1 --hint=multithread --time=01:00:00 --mem-per-cpu=1443  --partition=alpha` to lunch a simple MPI test code (like printing message from different MPI processors) instead of star_cluster_mpi.sh petar. If the same error appears, it suggests that the MPI environment is not properly configured, such as inconsistent MPI versions are used for compiling and running.

**Comment by marlito-gonaldo-byte** [comment]
I ran a test mpi script, I get this warning :
```
--------------------------------------------------------------------------
WARNING: Could not generate an xpmem segment id for this process'
address space.

The vader shared memory BTL will fall back on another single-copy
mechanism if one is available. This may result in lower performance.

  Local host: i8034
  Error code: 2 (No such file or directory)
--------------------------------------------------------------------------
```
I need to figure out the xpmem warning.
From the support of the HPC I am using they told me they were able to run mpi benchmark with the module I am using.

**Comment by marlito-gonaldo-byte** [comment]
With the help of the HPC support I am investigating on the xpmem error. 
By changing in the script `mpirun -n 6 petar -u 1 -b 500 -t 10.0 -o 5.0 input &>output` to `srun petar -u 1 -b 500 -t 10.0 -o 5.0 input &>output` we are getting rid of this error : 
```
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 2 with PID 1876225 on node i8024 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
[i8024:1876207] 5 more processes have sent help message help-btl-vader.txt / xpmem-make-failed
[i8024:1876207] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
5 total processes killed (some possibly by mpirun during cleanup)
```
However the following error remain : 
```
--------------------------------------------------------------------------
WARNING: Could not generate an xpmem segment id for this process'
address space.

The vader shared memory BTL will fall back on another single-copy
mechanism if one is available. This may result in lower performance.

  Local host: i8034
  Error code: 2 (No such file or directory)
--------------------------------------------------------------------------
```
It is printed 6 times in the petar output file (corresponding to the number of task per nodes I am asking), and another message is printed at the end : `srun: error: i8020: tasks 0-5: Segmentation fault (core dumped)`

The obvious issue is that there xpmem is missing from my OpenMP and MPI installation, so  I am trying to use the `--with-debug` option to be sure of the origin of the crash but I don't get more information in slurm output or in petar output file, nor `--with-debug=assert` nor `--with-debug=g` .
I checked the petar executable was indeed properly installed with debug option, so I just ran the script as I was doing it : 
`sbatch --nodes=1 --ntasks-per-node=6 --cpus-per-task=2 --gres=gpu:1 --hint=multithread --time=01:00:00 --mem-per-cpu=1443  --partition=alpha /projects/p_s_blackhole/workspace/PeTar/sample/star_cluster_mpi.sh`

Am I missing something on the way to use petar with debug ?

**Comment by marlito-gonaldo-byte** [comment]
Hello,
I am still unable to run jobs with MPI.
I discovered that the xpmem warning doesn't appear when I am connected to the HPC cluster without GPUs but in that case I still get `srun: error: i8020: tasks 0-5: Segmentation fault (core dumped)` 

I tried setting `OMP_STACKSIZE=512M` it didn't change anything.
I used `ulimit -s unlimited` it didn't change anything.

Please answer me this time. I need to fix this issue and start simulation as soon as possible.

**Comment by lwang-astro** [comment]
Sorry for the delay of reply. In your output file generated when run the star_cluster_mpi.sh script, did you see anything printed from petar code? The file continue the log starting from the FDPS logo, such as:
```
     //==================================\\
     ||                                  ||
     || ::::::: ::::::. ::::::. .::::::. ||
     || ::      ::    : ::    : ::       ||
     || ::::::  ::    : ::::::'  `:::::. ||
     || ::      ::::::' ::      `......' ||
     ||     Framework for Developing     ||
     ||        Particle Simulator        ||
     ||     Version 7.0 (2021/08)        ||
     \\==================================//

```
If this does not exist in output file, it means the petar code is not properly launched. 

Sometimes the system may has trouble to lunch a hybrid parallelization with both MPI and  OpenMP.
You can first try to disable OpenMP when you compile petar with `--disable-openmp` and use pure MPI and see whether the code works. If the code works, it suggests some problem of coupling MPI and OpenMP in your HPC. 

In addition, since you have attempted to compile Petar with the debug option `--with-debug=g`, another possible way to identify the actual problem is by using an interactive job. You can ask the administrator how to launch an interactive job on your HPC. In SLURM, the general command is like `srun -n2 -t02:00:00 --pty bash`, where `--pty bash` indicates that you want to use interactive mode, `-n2 -t02:00:00` indicates two core tasks with 2 hour time limits. In this mode, you will log directly into the computing nodes and can manually run petar there.

You can then use `gdb` to trace the exact problem occuring when running the code (make sure your code is configured with `--with-debug=g` and `make install` is used).
```
export OMP_STACKSIZE=128M
export OMP_NUM_THREADS=2
gdb --arg  petar -u 1 -b 500 -t 100.0 -o 5.0 input
```
You may need to familliarize yourself with the basics of using gdb.
Once `gdb` is started, you can type `run` to begin the simulation. If a segmentational fault occurs, it will stop and display the exact part of the code that triggerred the error. By typing `where`, you can see the full trackback of where the error occurred. 

Let me know whether these can help. Since you are in hurry, if necessary, we may also possible to find a suitable time for an online zoom meeting, then I can possible to see the details of problems.

**Comment by marlito-gonaldo-byte** [comment]
Thank you for this answer.
I compiled the code without openMP, indeed the error comes from MPI not the coupling of openMP and MPI.

I am running the code with gdb right now, it look like there is error of compatibility between HPC's library, the support should be able to help me.

Thank you for the suggestion of an online meeting, I will keep you updated.

**Comment by marlito-gonaldo-byte** [comment]
Hello, I finally solved this segmentation fault issue.
The problem seemed to be coming from misconfiguration between OpenMPI and UCX. 

I am now closing the issue thank you very much for your support. 

Best regards,
Maël
