### ISSUE TITLE
SC in SMBH potential not running

### ISSUE THREAD

**Issue by pavlikva** [lwang-astro/PeTar#54]
Hi,

I'm trying to set up simulations with a star cluster in the Galactic centre. For now, I've been trying to replicate the initial conditions you have in your 2022 paper with D. Lin (https://arxiv.org/pdf/2212.09215). However, the simulation is halting on time step 0 and the output file is full of n_ptcl and r_search log messages.

I had no issues running the same cluster in the MWPotential2014, but giving it the Keplerian potential with, e.g., --galpy-type-arg 7:19500.0 doesn't run.

Did you set up your code differently for your paper?

Thanks, Vaclav

**Comment by lwang-astro** [comment]
Your galpy option `--galpy-type-arg 7:19500.0` is not completed. The power law index of the power-law-sphere potential should be provided together, such as --galpy-type-arg 7:19500.0,3 for point-mass potential.
